import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const { data } = trpc.item.addItem.useQuery({ name: "from tRPC" });
  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 min-h-screen max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Shopping List</h2>
          <button className="p-transition  rounded-md bg-violet-500 p-2 text-sm text-white hover:bg-violet-600">
            My Cart
          </button>
        </div>
      </main>
    </>
  );
};

export default Home;
