import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

import ItemModal from "../components/ItemModal";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [modalOpen, setModalOpen] = useState(false);
  const { data, refetch, isLoading } = trpc.item.getAllItems.useQuery();
  const { mutateAsync: deleteList, error } = trpc.item.deleteItem.useMutation();
  const deleteListItem = async (id: string) => {
    try {
      await deleteList({ id });
      refetch();
    } catch (error) {
      console.log(error);
    }
  };
  if (error?.data) {
    // zodError will be inferred
    return <pre>Error: {JSON.stringify(error.data, null, 2)}</pre>;
  }
  if (!data || isLoading) return <>Loading...</>;
  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {modalOpen && <ItemModal setModalOpen={setModalOpen} refetch={refetch} />}
      <main className="mx-auto my-12 min-h-screen max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Shopping List</h2>
          <button
            onClick={() => setModalOpen(true)}
            className="p-transition  rounded-md bg-violet-500 p-2 text-sm text-white hover:bg-violet-600"
          >
            My Cart
          </button>
        </div>
        <ul className="mt-4">
          {data?.map((item) => (
            <li
              key={item.id}
              className="align-center mb-1 flex items-center justify-between"
            >
              <span>{item.name}</span>{" "}
              <button
                className="grid place-items-center bg-gray-50 px-2  text-sm  text-red-500"
                onClick={() => deleteListItem(item.id)}
              >
                x
              </button>
            </li>
          ))}
        </ul>
      </main>
    </>
  );
};

export default Home;
