import { type WebDevComment } from "@prisma/client";
import Head from "next/head";
import { useRouter } from "next/router";
import React, { useMemo } from "react";
import { RTQ_VARIABLES } from "../../constant";
import { trpc } from "../../utils/trpc";

const Post = () => {
  const router = useRouter();
  const id = router.query.id as string;
  const { data, isLoading, error } = trpc.comments.getPostById.useQuery(
    {
      id: id as string,
    },
    {
      ...RTQ_VARIABLES,
      enabled: !!id,
    }
  );


  return (
    <>
      <Head>
        <title>{isLoading || !data ? "Loading..." : data.title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 min-h-screen max-w-3xl">
        {error && <h5 className="error-msg">{error.message}</h5>}
        {isLoading || !data ? (
          <h1>Loading...</h1>
        ) : (
          <>
            <h1>{data.title}</h1>
            <article>{data.body}</article>
            <div className="comments-title">Comments</div>
            <section>
              {data.comments.map((comment) => (
                <div key={comment.id} className="comment">
                  <div className="comment-body">{comment.message}</div>
                  <div className="comment-author">{comment.user.name}</div>
                </div>
              ))}
            </section>
          </>
        )}
      </main>
    </>
  );
};

export default Post;
