import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../../utils/trpc";
// refetchInterval: 20000,
// refetchIntervalInBackground: true,
// staleTime: 10000,
// cacheTime: 10000,
const Comments: NextPage = () => {
  const { data, isLoading, error } = trpc.comments.getAllPosts.useQuery();
  return (
    <>
      <Head>
        <title>Nested Comments</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mx-auto my-12 min-h-screen max-w-3xl">
        <ul>
          {error && <h1>{error.message}</h1>}
          {isLoading || !data ? (
            <h1>Loading...</h1>
          ) : (
            data.map((post) => (
              <Link href={`/post/${post.id}`} key={post.id}>
                <h2>{post.title}</h2>
              </Link>
            ))
          )}
        </ul>
      </main>
    </>
  );
};

export default Comments;
